<?

    $showSravn = true;
    require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");

    $APPLICATION->SetPageProperty("keywords", "Интернет-магазин Мамин городок");
    $APPLICATION->SetPageProperty("title", "Интернет магазин детских пеленальных комодов");
    $APPLICATION->SetTitle("Каталог");
    $order = $APPLICATION->GetCurPageParam("sort=price",array("sort"), false);
?>         

<?
    /*$APPLICATION->IncludeComponent(
    "bitrix:catalog", 
    ".default", 
    array(
    "IBLOCK_TYPE" => "catalog",
    "IBLOCK_ID" => "2",
    "BASKET_URL" => "/personal/basket.php",
    "ACTION_VARIABLE" => "action",
    "PRODUCT_ID_VARIABLE" => "id",
    "SECTION_ID_VARIABLE" => "SECTION_ID",
    "SEF_MODE" => "Y",
    "SEF_FOLDER" => "/catalog/",
    "AJAX_MODE" => "N",
    "AJAX_OPTION_JUMP" => "N",
    "AJAX_OPTION_STYLE" => "Y",
    "AJAX_OPTION_HISTORY" => "N",
    "CACHE_TYPE" => "N",
    "CACHE_TIME" => "36000000",
    "CACHE_'FILTER'" => "N",
    "CACHE_GROUPS" => "Y",
    "SET_TITLE" => "Y",
    "SET_STATUS_404" => "N",
    "USE_FILTER" => "N",
    "USE_REVIEW" => "N",
    "USE_COMPARE" => "N",
    "PRICE_CODE" => array(
    ),
    "USE_PRICE_COUNT" => "N",
    "SHOW_PRICE_COUNT" => "1",
    "PRICE_VAT_INCLUDE" => "Y",
    "PRICE_VAT_SHOW_VALUE" => "N",
    "SHOW_TOP_ELEMENTS" => "N",
    "PAGE_ELEMENT_COUNT" => "18",
    "LINE_ELEMENT_COUNT" => "3",
    "ELEMENT_SORT_FIELD" => "sort",
    "ELEMENT_SORT_ORDER" => "asc",
    "LIST_PROPERTY_CODE" => array(
    0 => "OLD_PRICE",
    1 => "PRICE",
    2 => "WISHES",
    3 => "RATING",
    4 => "VOTES",
    5 => "CH_TYPE",
    6 => "CH_PODUCER",
    7 => "",
    ),
    "INCLUDE_SUBSECTIONS" => "Y",
    "LIST_META_KEYWORDS" => "-",
    "LIST_META_DESCRIPTION" => "-",
    "LIST_BROWSER_TITLE" => "NAME",
    "DETAIL_PROPERTY_CODE" => array(
    0 => "OLD_PRICE",
    1 => "PRICE",
    2 => "WISHES",
    3 => "RATING",
    4 => "VOTES",
    5 => "CH_PRODUCER",
    6 => "",
    ),
    "DETAIL_META_KEYWORDS" => "keywords",
    "DETAIL_META_DESCRIPTION" => "description",
    "DETAIL_BROWSER_TITLE" => "title",
    "LINK_IBLOCK_TYPE" => "catalog",
    "LINK_IBLOCK_ID" => "3",
    "LINK_PROPERTY_SID" => "CML2_LINK",
    "LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
    "USE_ALSO_BUY" => "N",
    "DISPLAY_TOP_PAGER" => "Y",
    "DISPLAY_BOTTOM_PAGER" => "Y",
    "PAGER_TITLE" => "Товары",
    "PAGER_SHOW_ALWAYS" => "Y",
    "PAGER_TEMPLATE" => "",
    "PAGER_DESC_NUMBERING" => "N",
    "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
    "PAGER_SHOW_ALL" => "Y",
    "AJAX_OPTION_ADDITIONAL" => "",
    "HIDE_NOT_AVAILABLE" => "N",
    "ADD_SECTIONS_CHAIN" => "Y",
    "ADD_ELEMENT_CHAIN" => "N",
    "USE_ELEMENT_COUNTER" => "Y",
    "CONVERT_CURRENCY" => "N",
    "USE_PRODUCT_QUANTITY" => "Y",
    "ADD_PROPERTIES_TO_BASKET" => "Y",
    "PRODUCT_PROPS_VARIABLE" => "prop",
    "PARTIAL_PRODUCT_PROPERTIES" => "N",
    "PRODUCT_PROPERTIES" => array(
    ),
    "OFFERS_CART_PROPERTIES" => array(
    ),
    "SECTION_COUNT_ELEMENTS" => "Y",
    "SECTION_TOP_DEPTH" => "2",
    "ELEMENT_SORT_FIELD2" => "id",
    "ELEMENT_SORT_ORDER2" => "desc",
    "LIST_OFFERS_FIELD_CODE" => array(
    0 => "",
    1 => "",
    ),
    "LIST_OFFERS_PROPERTY_CODE" => array(
    0 => "",
    1 => "",
    ),
    "LIST_OFFERS_LIMIT" => "5",
    "DETAIL_CHECK_SECTION_ID_VARIABLE" => "N",
    "DETAIL_OFFERS_FIELD_CODE" => array(
    0 => "",
    1 => "",
    ),
    "DETAIL_OFFERS_PROPERTY_CODE" => array(
    0 => "",
    1 => "",
    ),
    "USE_STORE" => "N",
    "OFFERS_SORT_FIELD" => "sort",
    "OFFERS_SORT_ORDER" => "asc",
    "OFFERS_SORT_FIELD2" => "id",
    "OFFERS_SORT_ORDER2" => "desc",
    "PRODUCT_QUANTITY_VARIABLE" => "quantity",
    "SEF_URL_TEMPLATES" => array(
    "sections" => "",
    "section" => "#SECTION_CODE#/",
    "element" => "#SECTION_CODE#/#ELEMENT_CODE#/",
    "compare" => "compare.php?action=#ACTION_CODE#",
    ),
    "VARIABLE_ALIASES" => array(
    "compare" => array(
    "ACTION_CODE" => "action",
    ),
    )
    ),
    false
    );*/
?> 
<? 
    if($_COOKIE["namber_order"] == "checked"){
        $arrFilter["!PROPERTY_1498"] = false;
    }elseif($_COOKIE["namber_order"] == ""){
        if ($_GET["orderby"]=="CATALOG_PRICE_3")
            $arrFilter["!PROPERTY_1498"] = false;
        else
            $arrFilter["!PROPERTY_1498"] = true; 
    }                    
?>

<? $url_code = explode( '/', $APPLICATION->GetCurPage() );
    if($_GET["orderby"]){$sort_od = $_GET["orderby"];}else{$sort_od = "HAS_PREVIEW_PICTURE";};
    if($_GET["sort"]){$sort_a_d = $_GET["sort"];}else{$sort_a_d = "desc";};
    //   if($USER->IsAdmin()){  
    $arFilter = array('IBLOCK_ID' => 2);
    $rsParentSection = CIBlockSection::GetList( array(), $arFilter , false, Array('UF_SORT_TYPE_USER')); 
    while($rsParentSection_1 = $rsParentSection->Fetch()){
        if($url_code[2] == $rsParentSection_1["CODE"]){
            $xml_id_page = $rsParentSection_1['UF_SORT_TYPE_USER'];  
        }
    }
    Cmodule::IncludeModule('iblock');
    $rsEnum = CUserFieldEnum::GetList(array(), array("ID" => $xml_id_page))->GetNext();//$ID - id значения пользовательского поля типа список
    $xml_code_page = $rsEnum["XML_ID"];

    if($sort_od != "HAS_PREVIEW_PICTURE" and $_GET["orderby"] == ""){
        $code_section = $xml_code_page;
    }else{
        $code_section = $sort_od;
    }
    // arshow($code_section,true); 
    // }
    $APPLICATION->IncludeComponent(
	"bitrix:catalog", 
	"test", 
	array(
		"IBLOCK_TYPE" => "catalog",
		"IBLOCK_ID" => "2",
		"BASKET_URL" => "/personal/basket.php",
		"ACTION_VARIABLE" => "action",
		"PRODUCT_ID_VARIABLE" => "id",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"SEF_MODE" => "Y",
		"SEF_FOLDER" => "/catalog/",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "N",
		"SET_TITLE" => "N",
		"SET_STATUS_404" => "N",
		"USE_FILTER" => "Y",
		"USE_REVIEW" => "N",
		"USE_COMPARE" => "N",
		"PRICE_CODE" => array(
			0 => "Цена для выгрузки на сайт",
		),
		"USE_PRICE_COUNT" => "N",
		"SHOW_PRICE_COUNT" => "1",
		"PRICE_VAT_INCLUDE" => "Y",
		"PRICE_VAT_SHOW_VALUE" => "N",
		"SHOW_TOP_ELEMENTS" => "Y",
		"PAGE_ELEMENT_COUNT" => "20",
		"LINE_ELEMENT_COUNT" => "4",
		"ELEMENT_SORT_FIELD" => "PROPERTY_1498",
		"ELEMENT_SORT_ORDER" => "desc",
		"ELEMENT_SORT_FIELD2" => $code_section,
		"ELEMENT_SORT_ORDER2" => $sort_a_d,
		"LIST_PROPERTY_CODE" => array(
			0 => "CATALOG_AVAILABLE",
			1 => "CH_TYPE",
			2 => "CH_PODUCER",
			3 => "PROPERTY_1498",
			4 => "PREVIEW_PICTURE",
			5 => "HAS_PREVIEW_PICTURE",
			6 => "",
		),
		"INCLUDE_SUBSECTIONS" => "Y",
		"LIST_META_KEYWORDS" => "-",
		"LIST_META_DESCRIPTION" => "-",
		"LIST_BROWSER_TITLE" => "-",
		"DETAIL_PROPERTY_CODE" => array(
			0 => "CATALOG_AVAILABLE",
			1 => "PROIZVODITEL",
			2 => "PREVIEW_TEXT",
			3 => "USTANOVKA_NA_BAZU_ISOFIX",
			4 => "TIP",
			5 => "MATERIAL_BUTYLOCHKI",
			6 => "OBEM_POSUDY_ML",
			7 => "PHASH",
			8 => "UPDATE_HASH",
			9 => "ACTION",
			10 => "CML2_ARTICLE",
			11 => "CML2_BASE_UNIT",
			12 => "VIDEO",
			13 => "filters_section",
			14 => "SEO_H1",
			15 => "description",
			16 => "SEO_MODEL",
			17 => "SEO_MODEL_RUS",
			18 => "AVAILABLE",
			19 => "CML2_MANUFACTURER",
			20 => "RATING",
			21 => "WISH_RATING",
			22 => "SALE_RATING",
			23 => "CML2_TRAITS",
			24 => "SEO_TEXT",
			25 => "SERVICE_QSORT",
			26 => "DISCOUNT",
			27 => "SOSTAV_KOMPLEKTA",
			28 => "CML2_TAXES",
			29 => "title",
			30 => "SEO_TYPE",
			31 => "CML2_ATTRIBUTES",
			32 => "HIT",
			33 => "PRICE_CODE",
			34 => "CML2_BAR_CODE",
			35 => "BALDAKHIN",
			36 => "SALES_RATING",
			37 => "RECOMMENDED_BASKET",
			38 => "TIP_LYULKI",
			39 => "CHTO_VYBIRAEM",
			40 => "MATERIAL_BUTYLOCHKI_1",
			41 => "POTOK",
			42 => "OBEM_BUTYLOCHKI_ML",
			43 => "QU_ACTIVE",
			44 => "ANTI_KOLIKOVYY_KLAPAN",
			45 => "LYULKA",
			46 => "TIP_1",
			47 => "TIP_TOVARA",
			48 => "STATUS_TOVARA",
			49 => "OBEM_UPAKOVKI_M3",
			50 => "VOZRAST_OT_LET",
			51 => "MODEL",
			52 => "VID_TRANSFORMATSII",
			53 => "S_RUCHKAMI",
			54 => "NARUZHNIY_MATERIAL",
			55 => "MEKHOVOY",
			56 => "DLYA_PROGULOK",
			57 => "VES_UPAKOVKI_KG",
			58 => "UTEPLITEL",
			59 => "MATERIAL_PODKLADA",
			60 => "DLINA_SM",
			61 => "DLINA_SM_1",
			62 => "DLINA_SM_2",
			63 => "DLINA_SM_3",
			64 => "SHIRINA_SM",
			65 => "VYSOTA_SM",
			66 => "VES_KG",
			67 => "VES_KG_1",
			68 => "VES_KG_2",
			69 => "GLUBINA_SM",
			70 => "SKLADNOY",
			71 => "VID",
			72 => "MINIMALNYY_VES",
			73 => "MAKSIMALNYY_VES",
			74 => "MATERIAL_RYUKZAKI_KENGURU",
			75 => "POLOZHENIE_REBYENKA",
			76 => "TIP_SLINGA",
			77 => "NOVINKA",
			78 => "CEMNYY_CHEKHOL",
			79 => "TEKHNOLOGIYA_ZIMA_LETO",
			80 => "VID_1",
			81 => "KACHANIE",
			82 => "REGULIROVKA_NAKLONA_SPINKI",
			83 => "REMEN_BEZOPASNOSTI",
			84 => "PODVESNYE_IGRUSHKI",
			85 => "TRANSFORMER",
			86 => "VID_2",
			87 => "RADIUS_DEYSTVIYA_M",
			88 => "TIP_SIGNALA",
			89 => "RAZMER_SPALNOGO_MESTA",
			90 => "SEMNYY_STOLIK",
			91 => "REGULIROVKA_VYSOTY_STULCHIKA",
			92 => "RAZDELITEL_NOZHEK",
			93 => "PROKHODIMOST",
			94 => "MANEVRENOST",
			95 => "VID_3",
			96 => "VID_4",
			97 => "VID_5",
			98 => "VID_6",
			99 => "VID_7",
			100 => "VID_8",
			101 => "VID_9",
			102 => "VID_10",
			103 => "VID_11",
			104 => "VID_12",
			105 => "VID_13",
			106 => "VID_14",
			107 => "VID_15",
			108 => "VID_16",
			109 => "VID_17",
			110 => "VID_18",
			111 => "RAZMER_V_SLOZHENNOM_VIDE_VKHDKH_SH_SM",
			112 => "POL",
			113 => "TIP_IGRUSHKI",
			114 => "TIP_STULCHIKA",
			115 => "KOLESIKI",
			116 => "TIP_AKSESSUARA",
			117 => "RAZVIVAET",
			118 => "REGULIRUEMYY_NAKLON_SPINKI",
			119 => "PODSTAVKA_POD_NOZHKI",
			120 => "REMEN_BEZOPASNOSTI_1",
			121 => "KORZINA",
			122 => "TIP_MANEZHA",
			123 => "KOLESA",
			124 => "PELENALNYY_STOLIK",
			125 => "KOLYBEL",
			126 => "ZHESTKOE_DNO",
			127 => "MATRAC_V_KOMPLEKTE",
			128 => "ELEKTRONNYY_BLOK",
			129 => "IMPORT2YM_1",
			130 => "TIP_2",
			131 => "VID_TOVARA",
			132 => "KOLICHESTVO_KOLES",
			133 => "NAZNACHENIE",
			134 => "TIP_STOLIKA",
			135 => "NA_VYPISKU",
			136 => "SEZON",
			137 => "KOLICHESTVO_DETALEY",
			138 => "SERIYA",
			139 => "DLYA_DOMA",
			140 => "DLYA_ULITSY",
			141 => "TIP_KOLYASKI",
			142 => "KOLICHESTVO_MEST",
			143 => "MEKHANIZM_SKLADYVANIYA",
			144 => "GRUPPA",
			145 => "GOD_TESTA",
			146 => "ADAC_ITOGOVYY_REZULTAT",
			147 => "ADAC_BEZOPASNOST",
			148 => "ADAC_ISPOLZOVANIE_ERGONOMIKA_DO_2011G_",
			149 => "SEZON_1",
			150 => "ADAC_EKOLOGICHNOST_KOMFORT_DO_2011G_",
			151 => "DLINA_SM_4",
			152 => "ADAC_UKHOD",
			153 => "SHIRINA_SM_1",
			154 => "TIP_KROVATKI",
			155 => "MATERIAL_KROVATKI",
			156 => "MEKHANIZM_KACHANIYA",
			157 => "MAKSIMALNYY_ROST",
			158 => "MINIMALNYY_ROST",
			159 => "KOL_VO_KOLES",
			160 => "VYSOTA_SM_1",
			161 => "VES_KG_3",
			162 => "TIP_KREPLENIYA_V_AVTOMOBILE",
			163 => "POLOZHENIE_REBENKA",
			164 => "POVOROTNYY_MEKHANIZM",
			165 => "DOPOLNITELNAYA_ZASHCHITA_OT_BOKOVYKH_UDAROV",
			166 => "SOVMESTIMOST_S_TRANSPORTNYMI_SISTEMAMI",
			167 => "DLINA_SPALNOGO_MESTA_SM",
			168 => "SHIRINA_SPALNOGO_MESTA_SM",
			169 => "KOLESA_1",
			170 => "KOLICHESTVO_UROVNEY_VYSOTY_DNISHCHA",
			171 => "MAKSIMALNAYA_GLUBINA_SM",
			172 => "ANATOMICHESKAYA_PODUSHKA",
			173 => "DNISHCHE",
			174 => "VNUTRENNIE_REMNI",
			175 => "RAZMER_UPAKOVKI_D_KH_SH_KH_V_SM",
			176 => "REGULIROVKA_VYSOTY_VNUTRENNIKH_REMNEY",
			177 => "DLINA_UPAKOVKI_SM",
			178 => "SHIRINA_UPAKOVKI_SM",
			179 => "GORIZONTALNOE_POLOZHENIE_SPINKI",
			180 => "REGULIROVKA_NAKLONA_SPINKI_1",
			181 => "IZMENENIE_NAKLONA_PODLOKOTNIKA",
			182 => "OPUSKAYUSHCHAYASYA_PEREDNYAYA_STENKA",
			183 => "SEMNAYA_PEREDNYAYA_STENKA",
			184 => "REGULIRUEMYY_PO_VYSOTE_PODLOKOTNIK",
			185 => "REGULIROVKA_VYSOTY_PODGOLOVNIKA",
			186 => "MATERIAL_OBIVKI",
			187 => "RUCHKA_DLYA_PERENOSKI",
			188 => "VYNIMAYUSHCHIESYA_REYKI",
			189 => "ISPOLZOVANIE_V_KACHESTVE_KRESLA_KACHALKI",
			190 => "YASHCHIKI_POD_KROVATYU",
			191 => "VYSOTA_UPAKOVKI_SM",
			192 => "RAZMER_YASHCHIKOV",
			193 => "VSTROENNYY_KOMOD",
			194 => "PELENALNYY_STOL",
			195 => "VOZRAST_DO_MES",
			196 => "VOZRAST_OT_MES",
			197 => "OTDELENIE_KARMAN_DLYA_VESHCHEY",
			198 => "PODSTAKANNIK",
			199 => "SOLNTSEZASHCHITNYY_KOZYREK",
			200 => "SEMNYY_CHEKHOL",
			201 => "STRANA_PROIZVODITELYA",
			202 => "TIP_KOLES",
			203 => "GABARITY_V_SLOZHENNOM_VIDE",
			204 => "SHIRINA_SHASSI_SM",
			205 => "VES_SHASSI_KG",
			206 => "VES_LYULKI_KG",
			207 => "VES_PROGULOCHNOGO_BLOKA_KG",
			208 => "VES_AVTOKRESLA_PERENOSKI_KG",
			209 => "GABARITY_SPALNOGO_MESTA",
			210 => "GABARITY_SPALNOGO_MESTA_V_PROGULOCHNOM_BLOKE",
			211 => "POLOZHENIE_REBENKA_1",
			212 => "GORIZONTALNOE_POLOZHENIE_SPINKI_1",
			213 => "REGULIROVKA_NAKLONA_SPINKI_2",
			214 => "AMORTIZATORY",
			215 => "REMNI_BEZOPASNOSTI",
			216 => "LYULKA_PERENOSKA",
			217 => "BAMPER",
			218 => "PODNOZHKA",
			219 => "REGULIROVKA_PODNOZHKI",
			220 => "REGULIROVKA_RUCHKI_PO_VYSOTE",
			221 => "MATERIAL_TOVARA",
			222 => "CHEKHOL_NA_NOZHKI",
			223 => "KORZINA_1",
			224 => "SUMKA",
			225 => "NASOS",
			226 => "NAKIDKA_NA_NOZHKI",
			227 => "RAZMER_SPALNOGO_MESTA_1",
			228 => "TOLSHCHINA_SM",
			229 => "PRUZHINY",
			230 => "SEMNYY_CHEKHOL_1",
			231 => "VID_19",
			232 => "DOZHDEVIK",
			233 => "MATERIAL_KOMODA",
			234 => "NALICHIE_VANNOCHKI",
			235 => "NALICHIE_PELENALNOGO_STOLIKA",
			236 => "KOL_VO_YASHCHIKOV",
			237 => "TIP_KONVERTA",
			238 => "PROTIVOMOSKITNAYA_SETKA",
			239 => "PODSTAKANNIK_1",
			240 => "KOLYASKA_TRANSFORMER_DELTIM_VOYAGER",
			241 => "STATUS_NOMENKLATURY",
			242 => "ODEYALO",
			243 => "RASPRODAZHA",
			244 => "GARANTIYA_PROIZVODITELYA",
			245 => "VID_TEKHNIKI",
			246 => "VID_20",
			247 => "TIP_MOLOKOOTSOSA",
			248 => "REGULIROVKA_RITMA",
			249 => "REGULIROVKA_SKOROSTI",
			250 => "TIP_PODOGREVATELYA",
			251 => "TAYMER",
			252 => "TIP_STERILIZATORA",
			253 => "KOL_VO_BUTYLOCHEK",
			254 => "VID_21",
			255 => "OBEM_VANNY_L",
			256 => "TIP_TERMOMETRA",
			257 => "VID_22",
			258 => "VID_23",
			259 => "VID_24",
			260 => "PRIMENENIE",
			261 => "VID_25",
			262 => "UTEPLENNYY",
			263 => "AKTSIYA",
			264 => "VOZRAST_DO_LET",
			265 => "VIDY_TRANSFORMATSIY",
			266 => "KHIT_PRODAZH",
			267 => "URL_SIZE",
			268 => "SILIKONOVYE_NAKLADKI",
			269 => "ARTICUL",
			270 => "PLUS",
			271 => "MINUS",
			272 => "PRICE",
			273 => "LIKE",
			274 => "manufacturer_warrant",
			275 => "OLD_PRICE",
			276 => "ACCESSORIES",
			277 => "keywords",
			278 => "WISHES",
			279 => "NAME_VPAD",
			280 => "NAME_RPAD",
			281 => "SELLOUT",
			282 => "OLD_PRICE_TEXT",
			283 => "PRICE_TEXT",
			284 => "VOTES",
			285 => "RATING_SUM",
			286 => "FORUM_MESSAGE_CNT",
			287 => "FORUM_TOPIC_ID",
			288 => "STUL_TOVAR",
			289 => "SBOR",
			290 => "ELEVATOR",
			291 => "WO_ELEVATOR",
			292 => "_",
			293 => "__1",
			294 => "__2",
			295 => "",
		),
		"DETAIL_META_KEYWORDS" => "-",
		"DETAIL_META_DESCRIPTION" => "-",
		"DETAIL_BROWSER_TITLE" => "-",
		"LINK_IBLOCK_TYPE" => "1c_catalog",
		"LINK_IBLOCK_ID" => "3",
		"LINK_PROPERTY_SID" => "CML2_LINK",
		"LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
		"USE_ALSO_BUY" => "N",
		"DISPLAY_TOP_PAGER" => "Y",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Товары",
		"PAGER_SHOW_ALWAYS" => "Y",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "Y",
		"AJAX_OPTION_ADDITIONAL" => "",
		"HIDE_NOT_AVAILABLE" => "Y",
		"ADD_SECTIONS_CHAIN" => "Y",
		"ADD_ELEMENT_CHAIN" => "N",
		"USE_ELEMENT_COUNTER" => "Y",
		"CONVERT_CURRENCY" => "N",
		"USE_PRODUCT_QUANTITY" => "Y",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRODUCT_PROPERTIES" => array(
			0 => "SOSTAV_KOMPLEKTA",
		),
		"OFFERS_CART_PROPERTIES" => array(
		),
		"SECTION_COUNT_ELEMENTS" => "Y",
		"SECTION_TOP_DEPTH" => "2",
		"LIST_OFFERS_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"LIST_OFFERS_PROPERTY_CODE" => array(
			0 => "OLD_PRICE",
			1 => "",
		),
		"LIST_OFFERS_LIMIT" => "5",
		"DETAIL_CHECK_SECTION_ID_VARIABLE" => "N",
		"DETAIL_OFFERS_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"DETAIL_OFFERS_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"USE_STORE" => "Y",
		"OFFERS_SORT_FIELD" => "shows",
		"OFFERS_SORT_ORDER" => "asc",
		"OFFERS_SORT_FIELD2" => "shows",
		"OFFERS_SORT_ORDER2" => "asc",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"FILTER_NAME" => "arrFilter",
		"FILTER_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_PROPERTY_CODE" => array(
			0 => "",
			1 => "PROPERTY_1498",
			2 => "DETAIL_TEXT",
			3 => "",
		),
		"FILTER_PRICE_CODE" => array(
			0 => "Цена для выгрузки на сайт",
		),
		"FILTER_OFFERS_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_OFFERS_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"STORES" => array(
		),
		"USE_MIN_AMOUNT" => "Y",
		"USER_FIELDS" => array(
			0 => "",
			1 => "",
		),
		"FIELDS" => array(
			0 => "",
			1 => "",
		),
		"MIN_AMOUNT" => "10",
		"SHOW_EMPTY_STORE" => "Y",
		"SHOW_GENERAL_STORE_INFORMATION" => "N",
		"STORE_PATH" => "/store/#store_id#",
		"MAIN_TITLE" => "Наличие на складах",
		"ADD_PICT_PROP" => "-",
		"LABEL_PROP" => "-",
		"PRODUCT_DISPLAY_MODE" => "N",
		"OFFER_ADD_PICT_PROP" => "-",
		"OFFER_TREE_PROPS" => array(
			0 => "-",
			1 => "",
		),
		"SHOW_DISCOUNT_PERCENT" => "N",
		"SHOW_OLD_PRICE" => "N",
		"DETAIL_SHOW_MAX_QUANTITY" => "N",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_ADD_TO_BASKET" => "В корзину",
		"MESS_BTN_COMPARE" => "Сравнение",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_NOT_AVAILABLE" => "Нет в наличии",
		"DETAIL_USE_VOTE_RATING" => "N",
		"DETAIL_USE_COMMENTS" => "N",
		"FILTER_VIEW_MODE" => "VERTICAL",
		"SECTIONS_VIEW_MODE" => "TEXT",
		"SECTIONS_SHOW_PARENT_NAME" => "Y",
		"OFFERS_FIELDS" => array(
			0 => "NAME",
			1 => "",
		),
		"OFFERS_PROPERTIES" => array(
			0 => "",
			1 => "",
		),
		"COMPONENT_TEMPLATE" => "test",
		"TOP_ELEMENT_COUNT" => "4",
		"TOP_LINE_ELEMENT_COUNT" => "4",
		"TOP_ELEMENT_SORT_FIELD" => "shows",
		"TOP_ELEMENT_SORT_ORDER" => "PROPERTY_1498",
		"TOP_ELEMENT_SORT_FIELD2" => "shows",
		"TOP_ELEMENT_SORT_ORDER2" => "asc",
		"TOP_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"TOP_OFFERS_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"TOP_OFFERS_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"TOP_OFFERS_LIMIT" => "4",
		"DETAIL_SET_CANONICAL_URL" => "N",
		"SHOW_DEACTIVATED" => "N",
		"USE_MAIN_ELEMENT_SECTION" => "N",
		"SET_LAST_MODIFIED" => "N",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SHOW_404" => "N",
		"MESSAGE_404" => "",
		"SECTION_BACKGROUND_IMAGE" => "-",
		"DETAIL_BACKGROUND_IMAGE" => "-",
		"DISABLE_INIT_JS_IN_COMPONENT" => "N",
		"DETAIL_SET_VIEWED_IN_COMPONENT" => "N",
		"USE_GIFTS_DETAIL" => "Y",
		"USE_GIFTS_SECTION" => "Y",
		"USE_GIFTS_MAIN_PR_SECTION_LIST" => "Y",
		"GIFTS_DETAIL_PAGE_ELEMENT_COUNT" => "3",
		"GIFTS_DETAIL_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_DETAIL_BLOCK_TITLE" => "Выберите один из подарков",
		"GIFTS_DETAIL_TEXT_LABEL_GIFT" => "Подарок",
		"GIFTS_SECTION_LIST_PAGE_ELEMENT_COUNT" => "3",
		"GIFTS_SECTION_LIST_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_SECTION_LIST_BLOCK_TITLE" => "Подарки к товарам этого раздела",
		"GIFTS_SECTION_LIST_TEXT_LABEL_GIFT" => "Подарок",
		"GIFTS_SHOW_DISCOUNT_PERCENT" => "Y",
		"GIFTS_SHOW_OLD_PRICE" => "Y",
		"GIFTS_SHOW_NAME" => "Y",
		"GIFTS_SHOW_IMAGE" => "Y",
		"GIFTS_MESS_BTN_BUY" => "Выбрать",
		"GIFTS_MAIN_PRODUCT_DETAIL_PAGE_ELEMENT_COUNT" => "3",
		"GIFTS_MAIN_PRODUCT_DETAIL_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_MAIN_PRODUCT_DETAIL_BLOCK_TITLE" => "Выберите один из товаров, чтобы получить подарок",
		"SEF_URL_TEMPLATES" => array(
			"sections" => "",
			"section" => "#SECTION_CODE#/",
			"element" => "#SECTION_CODE#/#ELEMENT_CODE#/",
			"compare" => "compare.php?action=#ACTION_CODE#",
			"smart_filter" => "#SECTION_CODE#/filter/#SMART_FILTER_PATH#/",
		),
		"VARIABLE_ALIASES" => array(
			"compare" => array(
				"ACTION_CODE" => "action",
			),
		)
	),
	false
);
    /*                 // неполный вывод свойств товара
    "DETAIL_PROPERTY_CODE" => array(
    0 => "PROIZVODITEL",
    1 => "SOSTAV_KOMPLEKTA",
    2 => "BALDAKHIN",
    3 => "TIP_LYULKI",
    4 => "CHTO_VYBIRAEM",
    5 => "MATERIAL_BUTYLOCHKI_1",
    6 => "POTOK",
    7 => "OBEM_BUTYLOCHKI_ML",
    8 => "ANTI_KOLIKOVYY_KLAPAN",
    9 => "LYULKA",
    10 => "TIP_1",
    11 => "TIP_TOVARA",
    12 => "STATUS_TOVARA",
    13 => "OBEM_UPAKOVKI_M3",
    14 => "VOZRAST_OT_LET",
    15 => "MODEL",
    16 => "VID_TRANSFORMATSII",
    17 => "S_RUCHKAMI",
    18 => "NARUZHNIY_MATERIAL",
    19 => "MEKHOVOY",
    20 => "DLYA_PROGULOK",
    21 => "VES_UPAKOVKI_KG",
    22 => "UTEPLITEL",
    23 => "MATERIAL_PODKLADA",
    24 => "DLINA_SM_3",
    25 => "SHIRINA_SM",
    26 => "VYSOTA_SM",
    27 => "VES_KG_2",
    28 => "GLUBINA_SM",
    29 => "SKLADNOY",
    30 => "VID",
    31 => "MATERIAL_RYUKZAKI_KENGURU",
    32 => "POLOZHENIE_REBYENKA",
    33 => "TIP_SLINGA",
    34 => "NOVINKA",
    35 => "CEMNYY_CHEKHOL",
    36 => "TEKHNOLOGIYA_ZIMA_LETO",
    37 => "KACHANIE",
    38 => "REGULIROVKA_NAKLONA_SPINKI",
    39 => "REMEN_BEZOPASNOSTI",
    40 => "PODVESNYE_IGRUSHKI",
    41 => "TRANSFORMER",
    42 => "RADIUS_DEYSTVIYA_M",
    43 => "TIP_SIGNALA",
    44 => "RAZMER_SPALNOGO_MESTA",
    45 => "SEMNYY_STOLIK",
    46 => "REGULIROVKA_VYSOTY_STULCHIKA",
    47 => "RAZDELITEL_NOZHEK",
    48 => "PROKHODIMOST",
    49 => "MANEVRENOST",
    50 => "VID_18",
    51 => "RAZMER_V_SLOZHENNOM_VIDE_VKHDKH_SH_SM",
    52 => "POL",
    53 => "TIP_IGRUSHKI",
    54 => "TIP_STULCHIKA",
    55 => "KOLESIKI",
    56 => "TIP_AKSESSUARA",
    57 => "RAZVIVAET",
    58 => "REGULIRUEMYY_NAKLON_SPINKI",
    59 => "PODSTAVKA_POD_NOZHKI",
    60 => "REMEN_BEZOPASNOSTI_1",
    61 => "KORZINA",
    62 => "TIP_MANEZHA",
    63 => "KOLESA",
    64 => "PELENALNYY_STOLIK",
    65 => "KOLYBEL",
    66 => "ZHESTKOE_DNO",
    67 => "MATRAC_V_KOMPLEKTE",
    68 => "ELEKTRONNYY_BLOK",
    69 => "IMPORT2YM_1",
    70 => "TIP_2",
    71 => "VID_TOVARA",
    72 => "KOLICHESTVO_KOLES",
    73 => "NAZNACHENIE",
    74 => "TIP_STOLIKA",
    75 => "NA_VYPISKU",
    76 => "SEZON",
    77 => "KOLICHESTVO_DETALEY",
    78 => "SERIYA",
    79 => "DLYA_DOMA",
    80 => "DLYA_ULITSY",
    81 => "TIP_KOLYASKI",
    82 => "KOLICHESTVO_MEST",
    83 => "MEKHANIZM_SKLADYVANIYA",
    84 => "GRUPPA",
    85 => "GOD_TESTA",
    86 => "ADAC_ITOGOVYY_REZULTAT",
    87 => "ADAC_BEZOPASNOST",
    88 => "ADAC_ISPOLZOVANIE_ERGONOMIKA_DO_2011G_",
    89 => "SEZON_1",
    90 => "SOLNTSEZASHCHITNYY_KOZYREK",
    91 => "SILIKONOVYE_NAKLADKI",
    92 => "STRANA_PROIZVODITELYA",
    93 => "TIP_KOLES",
    94 => "GABARITY_V_SLOZHENNOM_VIDE",
    95 => "SHIRINA_SHASSI_SM",
    96 => "VES_SHASSI_KG",
    97 => "VES_LYULKI_KG",
    98 => "VES_PROGULOCHNOGO_BLOKA_KG",
    99 => "VES_AVTOKRESLA_PERENOSKI_KG",
    100 => "GABARITY_SPALNOGO_MESTA",
    101 => "GABARITY_SPALNOGO_MESTA_V_PROGULOCHNOM_BLOKE",
    102 => "POLOZHENIE_REBENKA_1",
    103 => "GORIZONTALNOE_POLOZHENIE_SPINKI_1",
    104 => "REGULIROVKA_NAKLONA_SPINKI_2",
    105 => "AMORTIZATORY",
    106 => "REMNI_BEZOPASNOSTI",
    107 => "LYULKA_PERENOSKA",
    108 => "BAMPER",
    109 => "PODNOZHKA",
    110 => "REGULIROVKA_PODNOZHKI",
    111 => "REGULIROVKA_RUCHKI_PO_VYSOTE",
    112 => "CHEKHOL_NA_NOZHKI",
    113 => "KORZINA_1",
    114 => "SUMKA",
    115 => "NASOS",
    116 => "NAKIDKA_NA_NOZHKI",
    117 => "RAZMER_SPALNOGO_MESTA_1",
    118 => "TOLSHCHINA_SM",
    119 => "PRUZHINY",
    120 => "SEMNYY_CHEKHOL_1",
    121 => "DOZHDEVIK",
    122 => "MATERIAL_KOMODA",
    123 => "NALICHIE_VANNOCHKI",
    124 => "NALICHIE_PELENALNOGO_STOLIKA",
    125 => "KOL_VO_YASHCHIKOV",
    126 => "TIP_KONVERTA",
    127 => "PROTIVOMOSKITNAYA_SETKA",
    128 => "PODSTAKANNIK_1",
    129 => "KOLYASKA_TRANSFORMER_DELTIM_VOYAGER",
    130 => "STATUS_NOMENKLATURY",
    131 => "ODEYALO",
    132 => "RASPRODAZHA",
    133 => "GARANTIYA_PROIZVODITELYA",
    134 => "VID_TEKHNIKI",
    135 => "TIP_MOLOKOOTSOSA",
    136 => "REGULIROVKA_RITMA",
    137 => "REGULIROVKA_SKOROSTI",
    138 => "TIP_PODOGREVATELYA",
    139 => "TAYMER",
    140 => "TIP_STERILIZATORA",
    141 => "KOL_VO_BUTYLOCHEK",
    142 => "OBEM_VANNY_L",
    143 => "TIP_TERMOMETRA",
    144 => "PRIMENENIE",
    145 => "VID_25",
    146 => "UTEPLENNYY",
    147 => "AKTSIYA",
    148 => "VOZRAST_DO_LET",
    149 => "VIDY_TRANSFORMATSIY",
    150 => "KHIT_PRODAZH",
    151 => "ARTICUL",
    152 => "PLUS",
    153 => "MINUS",
    154 => "PRICE",
    155 => "LIKE",
    156 => "manufacturer_warrant",
    157 => "OLD_PRICE",
    158 => "ACCESSORIES",
    159 => "VIDEO",
    160 => "keywords",
    161 => "WISHES",
    162 => "NAME_VPAD",
    163 => "NAME_RPAD",
    164 => "SELLOUT",
    165 => "OLD_PRICE_TEXT",
    166 => "PRICE_TEXT",
    167 => "VOTES",
    168 => "RATING_SUM",
    169 => "FORUM_MESSAGE_CNT",
    170 => "FORUM_TOPIC_ID",
    171 => "STUL_TOVAR",
    172 => "SBOR",
    173 => "ELEVATOR",
    174 => "WO_ELEVATOR",
    175 => "_",
    176 => "__1",
    177 => "__2",
    178 => "VES_KG",
    179 => "VES_KG_1",
    180 => "VYSOTA_SM_1",
    181 => "VYSOTA_UPAKOVKI_SM",
    182 => "DLINA_UPAKOVKI_SM",
    183 => "SHIRINA_UPAKOVKI_SM",
    184 => "SHIRINA_SPALNOGO_MESTA_SM",
    185 => "SHIRINA_SM_1",
    186 => "YASHCHIKI_POD_KROVATYU",
    187 => "KOLICHESTVO_UROVNEY_VYSOTY_DNISHCHA",
    188 => "MEKHANIZM_KACHANIYA",
    189 => "MEKHANIZM_KACHANIYA",
    190 => "MEKHANIZM_KACHANIYA",
    191 => "MEKHANIZM_KACHANIYA",

    */

require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");