<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Сообщество");
?>

<?$APPLICATION->IncludeComponent("individ:socialnetwork", ".default", array(
	"ITEM_DETAIL_COUNT" => "32",
	"ITEM_MAIN_COUNT" => "6",
	"DATE_TIME_FORMAT" => "d.m.Y H:i:s",
	"NAME_TEMPLATE" => "#NOBR##LAST_NAME# #NAME##/NOBR#",
	"SHOW_LOGIN" => "Y",
	"CAN_OWNER_EDIT_DESKTOP" => "Y",
	"SM_THEME" => "grey",
	"USE_MAIN_MENU" => "N",
	"USE_SHARE" => "N",
	"SHOW_RATING" => "N",
	"PATH_TO_SEARCH_EXTERNAL" => "",
	"SEF_MODE" => "Y",
	"SEF_FOLDER" => "/community/",
	"CACHE_TYPE" => "A",
	"CACHE_TIME" => "3600",
	"CACHE_TIME_LONG" => "604800",
	"PATH_TO_SMILE" => "/bitrix/images/socialnetwork/smile/",
	"PATH_TO_BLOG_SMILE" => "/bitrix/images/blog/smile/",
	"PATH_TO_FORUM_SMILE" => "/bitrix/images/forum/smile/",
	"SONET_PATH_TO_FORUM_ICON" => "/bitrix/images/forum/icon/",
	"SET_TITLE" => "Y",
	"SET_NAV_CHAIN" => "Y",
	"LOG_SUBSCRIBE_ONLY" => "N",
	"LOG_RSS_TTL" => "60",
	"USER_FIELDS_MAIN" => array(
	),
	"USER_PROPERTY_MAIN" => array(
	),
	"USER_FIELDS_CONTACT" => array(
	),
	"USER_PROPERTY_CONTACT" => array(
	),
	"USER_FIELDS_PERSONAL" => array(
	),
	"USER_PROPERTY_PERSONAL" => array(
	),
	"GROUP_PROPERTY" => array(
	),
	"GROUP_USE_BAN" => "Y",
	"EDITABLE_FIELDS" => array(
		0 => "LOGIN",
		1 => "NAME",
		2 => "SECOND_NAME",
		3 => "LAST_NAME",
		4 => "EMAIL",
		5 => "PERSONAL_BIRTHDAY",
		6 => "PERSONAL_WWW",
		7 => "PERSONAL_ICQ",
		8 => "PERSONAL_GENDER",
		9 => "PERSONAL_PHOTO",
		10 => "PERSONAL_PHONE",
		11 => "PERSONAL_FAX",
		12 => "PERSONAL_MOBILE",
		13 => "PERSONAL_PAGER",
		14 => "PERSONAL_COUNTRY",
		15 => "PERSONAL_STATE",
		16 => "PERSONAL_CITY",
		17 => "PERSONAL_ZIP",
		18 => "PERSONAL_STREET",
		19 => "PERSONAL_MAILBOX",
	),
	"SHOW_YEAR" => "Y",
	"USER_FIELDS_SEARCH_SIMPLE" => array(
		0 => "PERSONAL_GENDER",
		1 => "PERSONAL_CITY",
	),
	"USER_PROPERTIES_SEARCH_SIMPLE" => array(
	),
	"USER_FIELDS_SEARCH_ADV" => array(
		0 => "PERSONAL_GENDER",
		1 => "PERSONAL_COUNTRY",
		2 => "PERSONAL_CITY",
	),
	"USER_PROPERTIES_SEARCH_ADV" => array(
	),
	"SONET_USER_FIELDS_LIST" => array(
		0 => "PERSONAL_BIRTHDAY",
		1 => "PERSONAL_GENDER",
		2 => "PERSONAL_CITY",
	),
	"SONET_USER_PROPERTY_LIST" => array(
	),
	"SONET_USER_FIELDS_SEARCHABLE" => array(
		0 => "LOGIN",
		1 => "NAME",
		2 => "SECOND_NAME",
		3 => "LAST_NAME",
		4 => "PERSONAL_BIRTHDAY",
		5 => "PERSONAL_BIRTHDAY_YEAR",
		6 => "PERSONAL_BIRTHDAY_DAY",
		7 => "PERSONAL_GENDER",
		8 => "PERSONAL_COUNTRY",
		9 => "PERSONAL_STATE",
		10 => "PERSONAL_CITY",
		11 => "PERSONAL_ZIP",
		12 => "PERSONAL_STREET",
		13 => "PERSONAL_MAILBOX",
		14 => "WORK_COMPANY",
		15 => "WORK_DEPARTMENT",
		16 => "WORK_POSITION",
		17 => "WORK_COUNTRY",
		18 => "WORK_STATE",
		19 => "WORK_CITY",
		20 => "WORK_ZIP",
		21 => "WORK_STREET",
		22 => "WORK_MAILBOX",
	),
	"SONET_USER_PROPERTY_SEARCHABLE" => array(
	),
	"ALLOW_GROUP_CREATE_REDIRECT_REQUEST" => "Y",
	"ALLOW_RATING_SORT" => "N",
	"BLOG_GROUP_ID" => "1",
	"ALLOW_POST_MOVE" => "N",
	"BLOG_IMAGE_MAX_WIDTH" => "800",
	"BLOG_IMAGE_MAX_HEIGHT" => "800",
	"BLOG_COMMENT_ALLOW_VIDEO" => "N",
	"BLOG_SHOW_SPAM" => "N",
	"BLOG_NO_URL_IN_COMMENTS" => "",
	"BLOG_NO_URL_IN_COMMENTS_AUTHORITY" => "",
	"BLOG_ALLOW_POST_CODE" => "Y",
	"BLOG_USE_GOOGLE_CODE" => "Y",
	"FORUM_ID" => "1",
	"FORUM_THEME" => "blue",
	"PHOTO_USER_IBLOCK_TYPE" => "catalog",
	"PHOTO_USER_IBLOCK_ID" => "2",
	"PHOTO_GROUP_IBLOCK_TYPE" => "catalog",
	"PHOTO_GROUP_IBLOCK_ID" => "2",
	"PHOTO_MODERATION" => "N",
	"PHOTO_SECTION_PAGE_ELEMENTS" => "15",
	"PHOTO_ELEMENTS_PAGE_ELEMENTS" => "50",
	"PHOTO_SLIDER_COUNT_CELL" => "3",
	"CELL_COUNT" => "0",
	"PHOTO_ALBUM_PHOTO_THUMBS_SIZE" => "150",
	"PHOTO_ALBUM_PHOTO_SIZE" => "150",
	"PHOTO_THUMBS_SIZE" => "250",
	"PHOTO_PREVIEW_SIZE" => "700",
	"PHOTO_ORIGINAL_SIZE" => "0",
	"PHOTO_WATERMARK_MIN_PICTURE_SIZE" => "200",
	"PHOTO_PATH_TO_FONT" => "",
	"PHOTO_SHOW_WATERMARK" => "Y",
	"PHOTO_WATERMARK_RULES" => "USER",
	"PHOTO_PHOTO_UPLOAD_MAX_FILESIZE" => "100",
	"PHOTO_USE_RATING" => "N",
	"PHOTO_USE_COMMENTS" => "N",
	"SEARCH_DEFAULT_SORT" => "rank",
	"SEARCH_PAGE_RESULT_COUNT" => "1",
	"SEARCH_TAGS_PAGE_ELEMENTS" => "100",
	"SEARCH_TAGS_PERIOD" => "",
	"SEARCH_TAGS_FONT_MAX" => "50",
	"SEARCH_TAGS_FONT_MIN" => "10",
	"SEARCH_TAGS_COLOR_NEW" => "3E74E6",
	"SEARCH_TAGS_COLOR_OLD" => "C0C0C0",
	"SEARCH_FILTER_NAME" => "sonet_search_filter",
	"SEARCH_FILTER_DATE_NAME" => "sonet_search_filter_date",
	"SEF_URL_TEMPLATES" => array(
		"index" => "index.php",
		"user" => "user/#user_id#/",
		"user_friends" => "user/#user_id#/friends/",
		"user_friends_add" => "user/#user_id#/friends/add/",
		"user_friends_delete" => "user/#user_id#/friends/delete/",
		"user_groups" => "user/#user_id#/groups/",
		"user_groups_add" => "user/#user_id#/groups/add/",
		"group_create" => "user/#user_id#/groups/create/",
		"user_profile_edit" => "user/#user_id#/edit/",
		"user_settings_edit" => "user/#user_id#/settings/",
		"user_features" => "user/#user_id#/features/",
		"search" => "search/",
		"reindex" => "reindex.php",
		"group_content_search" => "groupgroup/#group_id#/search/",
		"user_content_search" => "user/#user_id#/search/",
		"group" => "groupgroup/#group_id#/",
		"group_search" => "groupgroup/search/",
		"group_search_subject" => "groupgroup/search/#subject_id#/",
		"group_edit" => "groupgroup/#group_id#/edit/",
		"group_delete" => "groupgroup/#group_id#/delete/",
		"group_request_search" => "groupgroup/#group_id#/user_search/",
		"user_request_group" => "groupgroup/#group_id#/user_request/",
		"group_requests" => "groupgroup/#group_id#/requests/",
		"group_requests_out" => "groupgroup/#group_id#/requests_out/",
		"group_mods" => "groupgroup/#group_id#/moderators/",
		"group_users" => "groupgroup/#group_id#/users/",
		"group_ban" => "groupgroup/#group_id#/ban/",
		"user_leave_group" => "groupgroup/#group_id#/user_leave/",
		"group_features" => "groupgroup/#group_id#/features/",
		"group_log" => "groupgroup/#group_id#/log/",
		"group_request_user" => "groupgroup/#group_id#/user/#user_id#/request/",
		"group_request_group_search" => "groupgroup/#user_id#/group_search/",
		"message_form" => "messages/form/#user_id#/",
		"message_form_mess" => "messages/chat/#user_id#/#message_id#/",
		"user_ban" => "messages/ban/",
		"messages_chat" => "messages/chat/#user_id#/",
		"messages_input" => "messages/input/",
		"messages_input_user" => "messages/input/#user_id#/",
		"messages_output" => "messages/output/",
		"messages_output_user" => "messages/output/#user_id#/",
		"messages_users" => "messages/",
		"messages_users_messages" => "messages/#user_id#/",
		"log" => "log/",
		"activity" => "user/#user_id#/activity/",
		"subscribe" => "subscribe/",
		"user_subscribe" => "user/#user_id#/subscribe/",
		"group_subscribe" => "groupgroup/#group_id#/subscribe/",
		"user_photo" => "user/#user_id#/photo/",
		"user_calendar" => "user/#user_id#/calendar/",
		"user_files" => "user/#user_id#/files/lib/#path#",
		"group_photo" => "groupgroup/#group_id#/photo/",
		"group_forum" => "groupgroup/#group_id#/forum/",
		"group_calendar" => "groupgroup/#group_id#/calendar/",
		"group_files" => "groupgroup/#group_id#/files/#path#",
		"user_blog" => "user/#user_id#/blog/",
		"user_blog_post_edit" => "user/#user_id#/blog/edit/#post_id#/",
		"user_blog_rss" => "user/#user_id#/blog/rss/#type#/",
		"user_blog_draft" => "user/#user_id#/blog/draft/",
		"user_blog_post" => "user/#user_id#/blog/#post_id#/",
		"user_blog_moderation" => "user/#user_id#/blog/moderation/",
		"user_microblog" => "user/#user_id#/microblog/",
		"user_microblog_post" => "user/#user_id#/microblog/#post_id#/",
		"user_forum" => "user/#user_id#/forum/",
		"user_forum_topic_edit" => "user/#user_id#/forum/edit/#topic_id#/",
		"user_forum_topic" => "user/#user_id#/forum/#topic_id#/",
		"group_blog" => "groupgroup/#group_id#/blog/",
		"group_blog_post_edit" => "groupgroup/#group_id#/blog/edit/#post_id#/",
		"group_blog_rss" => "groupgroup/#group_id#/blog/rss/#type#/",
		"group_blog_draft" => "groupgroup/#group_id#/blog/draft/",
		"group_blog_post" => "groupgroup/#group_id#/blog/#post_id#/",
		"group_blog_moderation" => "groupgroup/#group_id#/blog/moderation/",
		"group_microblog" => "groupgroup/#group_id#/microblog/",
		"group_microblog_post" => "groupgroup/#group_id#/microblog/#post_id#/",
		"group_forum_topic_edit" => "groupgroup/#group_id#/forum/edit/#topic_id#/",
		"group_forum_topic" => "groupgroup/#group_id#/forum/#topic_id#/",
		"bizproc" => "bizproc/",
		"bizproc_edit" => "bizproc/#task_id#/",
		"video_call" => "video/#user_id#/",
	)
	),
	false
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>